#!/bin/sh

first=$1
if [ -z "$first" ]; then
	first=1990
fi

success='???'

date > log.txt

for year in `seq "$first" -1 1962`; do
	echo >> log.txt
	echo -n "$year: " >> log.txt

	curl \
		--silent \
		https://user-api.coronatest.nl/vaccinatie/programma/booster/$year/NEE \
	| tee -a log.txt \
	> $year.txt

	echo >&2 "$year: `cat $year.txt`"
	grep 'Rate limit' $year.txt && exit 1

	if grep '{"success":true}' $year.txt ; then
		echo >&2 "$year is the year"
		success="$year"
		break
	fi

	# limit rate of requests
	sleep 2
done

echo >> log.txt
echo ---- >> log.txt

now="`date '+%Y-%m-%d %H:%M:%S'`"
cat template.html \
	| sed "s/YEAR/$success/" \
	| sed "s/WHEN/$now/" \
> index.html
