#!/bin/sh -x

die() { echo >&2 "$@" ; exit 1 ; }

./find-year "$@" || die "unable to find the year"

git add index.html log.txt || die "unable to add index"

git commit \
	-m "`grep '<h1>' index.html`"  \
|| die "unable to commit"

git push -f origin main:gh-pages \
|| die "unable to push"

echo "Success"
exit 0
